// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dscmdqzgnarxgdtbtuvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzY21kcXpnbmFyeGdkdGJ0dXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzA0NzgsImV4cCI6MjA2MjM0NjQ3OH0.xU4LKlKaumQNURfrHoN1LriGbI58G0G2_ZHzM8-RTto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);